### ISSUE TITLE
How to change color value in Picker by user input from outside of picker

### ISSUE THREAD

**Issue by yourabusufiyan** [narsenico/a-color-picker#12]
Hello! I've been trying to get user input value to change color ii Picker. I want user input value and change to picker color. I also tried to change "color" attr after user input. But, I didn't work.
Thanks

**Comment by yourAverageDeveloper** [comment]
yeah same problem here. I tried assigning a global variable to the picker you get in the change listener but it will work when the color is changed not before it.

**Comment by yourAverageDeveloper** [comment]
There is, however, a work around for this.
`let colorPicker = AColorPicker.createPicker({ attachTo: '.picker', color: '#3ac0ff' })`
Once you have a variable that has AColorPicker stored in it. You can now call
`colorPicker.color` to get the current color which would be **#3ac0ff**

**Comment by narsenico** [comment]
Also You can always access the controller via `ctrl` property of the `'.a-color-picker'` element inside your container.

```
let colorPicker = AColorPicker.createPicker({ attachTo: '.picker', color: '#3ac0ff' })
document.querySelector('.picker>.a-color-picker').ctrl.color = 'white';

colorPicker === document.querySelector('.picker>.a-color-picker').ctrl
```
