### ISSUE TITLE
cannot set palette

### ISSUE THREAD

**Issue by Kazem-ma79** [narsenico/a-color-picker#17]
Hi,
Please make a way to set palette dynamically from code side.
I'm trying to set it with jqAttr but it's not working.
Tnx for this useful tool.

**Comment by valentinbdv** [comment]
+1, do you when it will be available? It's a great color picker @narsenico

**Comment by narsenico** [comment]
v1.2.0
The property palette is now editable

```js
const a = AColorPicker.createPicker({
        palette: ['red', 'yellow']
});
a.palette = ['red', '#00ff00', 'rgb(0, 0, 255)'];

```

**Comment by valentinbdv** [comment]
It works like a charm! Thanks a lot ;)
