### ISSUE TITLE
Problem with import

### ISSUE THREAD

**Issue by valentinbdv** [narsenico/a-color-picker#2]
Is there a way to insert the library in a typescript module base project.

I have tried many things like :
```
import AColorPicker = require('a-color-picker');
```
But I alway get an empty object.

**Comment by narsenico** [comment]
Hi @valentinbdv,
install the version 1.0.6 and use this line of code to import the library in your module
`import * as AColorPicker from 'a-color-picker';`

**Comment by valentinbdv** [comment]
Works great! 

Thanks a lot for the update!
