### ISSUE TITLE
[Request] set color() silently

### ISSUE THREAD

**Issue by mafar** [narsenico/a-color-picker#21]
Hi,
 i can change picker color programatically by 
```
picker.color = [205, 220, 57];  // set color 
```
I need something like 
```
picker.colorSilent = '' ;  // set color , do not trigger change event !!!
```
OR
```
picker.color = '';  // set color empty string
// change event is triggered 
//  should return color as empty as well,  instead of black color
```

Is there a way to set color silently so that handle and canavs are updated but ```change``` event is not triggered.

I am trying to implement ```Clear``` and ```Cancel ``` functionality and when i click on  ```Clear``` button , i set ```picker.color='' //empty ''' but picker triggers ```change``` and sends me back black color hex.

It will be helfpful if either ```change``` event send color as empty string or null if set ```picker.color='' //empty '''  
Or
If I am able to set color silenty without triggering ```change``` so i can set value of colro to empty string internally.

I hope you understand my issue :)

**Comment by narsenico** [comment]
v1.2.1
```js
const a = AColorPicker.createPicker({});
a.setColor('red', true); // change event is not triggered
```

**Comment by mafar** [comment]
Thanx . now works flawlessly. 
Can you please add this pen in examples as this may help some users 
**a-color-picker qtip2 Integration**
https://codepen.io/mafar/pen/XWromjQ?editors=0010
