### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [narsenico/a-color-picker#3]
Good day @narsenico  I am a graphic designer and I want to contribute to your good project by proposing a logo design which i will be doing for free. I noticed that the project doesn't have a logo yet. If you will allow me i will begin my design asap. Thanks and best regards!

-Tobaloidee

**Comment by narsenico** [comment]
Sounds great! Thanks.

**Comment by Tobaloidee** [comment]
here's the readme mock up

![readme](https://user-images.githubusercontent.com/36028424/42192411-4fdc6024-7e9b-11e8-8f46-ecb23dcd288d.png)

**Comment by Tobaloidee** [comment]
should i make a PR and upload the files Sir?

**Comment by narsenico** [comment]
Sure

**Comment by Tobaloidee** [comment]
Here's the PR #4 @narsenico Thanks for accepting it to your good project! My best regards!

- Tobaloidee

**Comment by Tobaloidee** [comment]
Hi @narsenico  i have made some variations of the Logo design which you can get from this link

https://drive.google.com/drive/folders/1FnGDy8iW13ePO5ajflYNEU5kOGz3JcHB

Thanks!

-Tobaloidee
